var oUl = document.getElementById('banner_ul');
    var oLi = oUl.getElementsByTagName('li');
    var oLoveIcon = document.getElementById('love_icon');
    var oSecret = document.getElementById('secret_content');
    var oSbutton = oSecret.getElementsByTagName('button');
    var oSdiv = oSecret.getElementsByTagName('div');
    var oSi = oSecret.getElementsByTagName('i');
    var oIsplay = document.getElementById('isPlay');
    var oLast = document.getElementById('lastBtn');
    var oNext = document.getElementById('nextBtn');     
    var oAudio = document.getElementById('audio');
    var oPastTime = document.getElementById('past_time');
    var oCurrentTime = document.getElementById('current_time');
    var oControlBtn = document.getElementById('controlBtn');
    var oCp = document.getElementById('changpian');
    var oSongName = document.getElementById('song_name');
    var oMore = document.getElementById('more');
    var oNav = document.getElementById('nav');
    var oNavLi = oNav.getElementsByTagName('li');
    var oGururin = document.getElementById('gururin');
    var oGururinUl = oGururin.getElementsByTagName('ul')[0];
    var oGururinLi = oGururinUl.getElementsByTagName('li');
    oUl.innerHTML += oUl.innerHTML;
    oUl.style.width = (oLi.length * 240) + 'px';
    slideShow(oUl, oLi[0], 3000);
    var imgdeg = 0;// 爱心图标旋转角度
    var id = null;
    var cubedeg = 0// 旋转木马的角度